// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import managers "fance/app/tasks/managers"
import mock "github.com/stretchr/testify/mock"

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// RetrieveAll provides a mock function with given fields: ctx, page, limit
func (_m *Reader) RetrieveAll(ctx context.Context, page int, limit int) ([]managers.TaskInfo, error) {
	ret := _m.Called(ctx, page, limit)

	var r0 []managers.TaskInfo
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []managers.TaskInfo); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]managers.TaskInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
