// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import managers "fance/app/tasks/managers"
import mock "github.com/stretchr/testify/mock"

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, task
func (_m *Writer) Create(ctx context.Context, task *managers.TaskInfo) (*managers.TaskInfo, error) {
	ret := _m.Called(ctx, task)

	var r0 *managers.TaskInfo
	if rf, ok := ret.Get(0).(func(context.Context, *managers.TaskInfo) *managers.TaskInfo); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*managers.TaskInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *managers.TaskInfo) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, taskID
func (_m *Writer) Delete(ctx context.Context, taskID string) error {
	ret := _m.Called(ctx, taskID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, task
func (_m *Writer) Update(ctx context.Context, task *managers.TaskInfo) (*managers.TaskInfo, error) {
	ret := _m.Called(ctx, task)

	var r0 *managers.TaskInfo
	if rf, ok := ret.Get(0).(func(context.Context, *managers.TaskInfo) *managers.TaskInfo); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*managers.TaskInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *managers.TaskInfo) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
